#!perl

use 5.010001;
use strict;
use warnings;

use Text::CSV_XS;

# AUTHORITY
# DATE
# DIST
# VERSION

binmode STDIN, ':encoding(utf8)';
binmode STDOUT, ':encoding(utf8)';

my $csv = Text::CSV_XS->new({binary=>1});
while (my $row = $csv->getline(\*ARGV)) {
    print join("\t", @$row), "\n";
}

# ABSTRACT: Convert CSV to TSV
# PODNAME:

=head1 SYNOPSIS

 % csv2tsv INPUT.csv > OUTPUT.tsv


=head1 DESCRIPTION

B<Common notes for the utilities:>

Encoding: The utilities in this module/distribution accept and emit UTF8 text.


=head1 SEE ALSO

L<tsv2csv>

Other CSV-related utilities in L<App::CSVUtils>.

Other TSV-related utilities in L<App::TSVUtils>.

L<App::TextTableUtils>

L<App::SerializeUtils>
